name: EirViewer
options:
  bundleIdPrefix: com.eir
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

packages:
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: "5.0.0"

targets:
  EirViewer:
    type: application
    platform: iOS
    sources:
      - path: Sources/EirViewer
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: EirViewer.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.eir.viewer
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Yams
      - sdk: HealthKit.framework

  EirViewerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/EirViewerTests
    dependencies:
      - target: EirViewer
      - package: Yams
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: "YES"
